### ISSUE TITLE
Cryptocurreny Json File.

### ISSUE THREAD

**Issue by KmKalpana** [GeekGuy-29/OneStopInfo#118]
I want to work on this JSON file where I would like to add each crypto's id,  name, symbol, and image link.

**Comment by GeekGuy-29** [comment]
Hey @KmKalpana if you want to contribute then please go ahead, i'd love your contribution. The only issue is the repo has been reported and has been removed from Hacktoberfest ☹️ 
Yet if you don't care about that, i just wanna say, thank you for even considering this repo to contribute 
Really means a lot!
