### ISSUE TITLE
Add forking information to the Contributing.md file

### ISSUE THREAD

**Issue by GeekGuy-29** [GeekGuy-29/OneStopInfo#2]
Hey there!

Kindly add the information required to perfectly contribute In the repository.
These changes have to be made in [Contributing file](https://github.com/GeekGuy-29/OneStopInfo/blob/main/Contributing.md)

**Comment by kaustav202** [comment]
can I work on this @GeekGuy-29

**Comment by GeekGuy-29** [comment]
Anyone can contribute to this issue, each request will be considered but only quality Pull Request will be considered

**Comment by ayush4345** [comment]
hey, i would like to contribute to this issue

**Comment by GeekGuy-29** [comment]
Hey @ayush4345 you can start working on that, do some hefty amount of changes and send in the PR.
I'll just give it a Review and will merge if Perfect
And thanks for considering to contribute
Happy Hacktoberfest
