### ISSUE TITLE
Build a Repository Logo/Icon page

### ISSUE THREAD

**Issue by GeekGuy-29** [GeekGuy-29/OneStopInfo#28]
Hey there!
I want someone to either make a logo for the repository to showcase on different social media pages
Also, don't forget to mention urself in the logo like, made by:-

**Comment by spike-spiegel-21** [comment]
I will be able to create the logo as I have some experience with design, please assign me this task. Thank you.

**Comment by spike-spiegel-21** [comment]
@GeekGuy-29 I have made a PR. Please check. Regards.

**Comment by GeekGuy-29** [comment]
Yes @spike-spiegel-21 got you PR
Thank you for your efforts
