### ISSUE TITLE
Contributors in README.md?

### ISSUE THREAD

**Issue by priyanshumaitra** [GeekGuy-29/OneStopInfo#50]
Can I add contributors list in README.md?

**Comment by GeekGuy-29** [comment]
Hey @priyanshumaitra 
I think you can make a .md file listing all the contributors with pictures and GitHub links
and then link that file in the Readme.md
PS:- I'll assign this to you only and only if you promise to keep updating the new contributors to the list, I'll wait for your confirmation
Thanks for considering to contribute to this Repo
Really means a lot! 💖💖

**Comment by priyanshumaitra** [comment]
It will be updated automatically. And will show something like this below 👇
![image](https://user-images.githubusercontent.com/26964412/194334806-fed39d15-f22b-41b7-9edd-c950d2ae29ba.png)

**Comment by GeekGuy-29** [comment]
Alright @priyanshumaitra work on it
And ya just make it in any other file rather readme because it'll cluster it and link that file in the readme
Thank you for considering to contribute in this repo
Really means a lot!!
💖💖
