### ISSUE TITLE
Contents in readme file

### ISSUE THREAD

**Issue by Veerhan-glitch** [GeekGuy-29/OneStopInfo#90]
Hi can i add a content list containing all the file name, extension, language, basic disc and weather it is low code/ non code or Heavy code (and maybe even contributors to that file)?

**Comment by GeekGuy-29** [comment]
Hey @Veerhan-glitch I am so sorry, but, I'll prefer that you work on some other issue, there are plenty of them
And Readme doesn't need that much of Info
Hope you don't mind
<3

**Comment by Veerhan-glitch** [comment]
Alright I will.
Happy hacktoberfest!

**Comment by GeekGuy-29** [comment]
<3
